[package]
name = "gbemu"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.29"
test-log = "0.2.19"
paste = "1.0.15"
getopts = "0.2.24"
ftail = "0.3.1"
num-derive = "0.4.2"
num-traits = "0.2.19"
